name: szsf
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  request:
    name: Request SZSF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python supervisors/szsf.py
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            网页 ${{ secrets.SZSF_URL }} 已经可以使用！
